pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'fabric-loom') {
                useModule("net.fabricmc:fabric-loom:${requested.version}")
            }
        }
    }
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'hat-layers'
